"""
app/models/alert.py
─────────────────────────────────────────────────────────────────
Alerts table — stores anomaly alerts generated by rules or ML.

Relationships:
  Alert ∞──1 Patient (Many-to-One)
─────────────────────────────────────────────────────────────────
"""
import uuid
import enum
from sqlalchemy import Column, String, Text, Boolean, DateTime, ForeignKey, Enum as SAEnum
from sqlalchemy import Uuid as UUID, JSON as JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class AlertType(str, enum.Enum):
    blood_pressure = "blood_pressure"
    oxygen_level   = "oxygen_level"
    heart_rate     = "heart_rate"
    blood_sugar    = "blood_sugar"
    temperature    = "temperature"
    anomaly        = "anomaly"
    system         = "system"

class SeverityLevel(str, enum.Enum):
    low      = "low"
    medium   = "medium"
    high     = "high"
    critical = "critical"


class Alert(Base):
    __tablename__ = "alerts"

    alert_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # ── FK to Patients ────────────────────────────────────────
    patient_id = Column(
        UUID(as_uuid=True),
        ForeignKey("patients.patient_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Alert Details ─────────────────────────────────────────
    alert_type = Column(SAEnum(AlertType, name="alert_type", create_type=True), nullable=False)
    severity   = Column(SAEnum(SeverityLevel, name="severity_level", create_type=True), nullable=False)
    message    = Column(String(500), nullable=False)
    context    = Column(JSONB, nullable=True)  # To store the exact readings that triggered it
    
    # ── Status ────────────────────────────────────────────────
    is_resolved = Column(Boolean, nullable=False, default=False)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolved_by = Column(UUID(as_uuid=True), nullable=True) # Could FK to users if needed

    # ── Timestamps ────────────────────────────────────────────
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(),
                        onupdate=func.now(), nullable=False)

    # ── Relationships ─────────────────────────────────────────
    patient = relationship("Patient", back_populates="alerts")

    def __repr__(self) -> str:
        return f"<Alert id={self.alert_id} sev={self.severity} resolved={self.is_resolved}>"
